import numpy

def euclidean(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def sqeuclidean(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def cosine(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def cdist(a: numpy.ndarray, b: numpy.ndarray, metric: str) -> numpy.ndarray: ...
def pdist(a: numpy.ndarray, metric: str) -> numpy.ndarray: ...
