import numpy

def braycurtis(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def canberra(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def chebyshev(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def euclidean(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def sqeuclidean(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def manhattan(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def minkowski(a: numpy.ndarray, b: numpy.ndarray, p: float) -> float: ...
def cosine(a: numpy.ndarray, b: numpy.ndarray) -> float: ...
def cdist(
    a: numpy.ndarray,
    b: numpy.ndarray,
    metric: str,
    p: int | None = None,
) -> numpy.ndarray: ...
def pdist(
    a: numpy.ndarray,
    metric: str,
    p: int | None = None,
) -> numpy.ndarray: ...
